### ISSUE TITLE
Provide example files (esp Extended Newick)

### ISSUE THREAD

**Issue by hyanwong** [tgvaughan/icytree#40]
I'm finding it hard to locate an example extended newick file online. It would be really good to have an example to play with, one that loads properly into IcyTree and allows the various recombinant edges options to be explored.

**Comment by tgvaughan** [comment]
Hi @hyanwong, [this website] (http://dmi.uib.es/~gcardona/BioInfo/enewick.html) describes the format and has a couple of very simple example extended newick strings. You can paste these directly into the "Enter tree directly" dialog accessible from the File menu.  Alternatively [this nexus file](https://github.com/tgvaughan/icytree/files/832121/arg.nexus.txt) (please forgive the .txt extension - github doesn't allow files with a .nexus extension to be attached to issues) contains a simulated ARG.  Use of the Nexus format permits annotations of the extended newick format in the same way that it does for the original newick format.

Hope this helps!

**Comment by tgvaughan** [comment]
I should also say that the simulated example I attached is a better indicator of IcyTree's abilities with respect to networks.  Visualization of networks is difficult, and it's very hard to have a single strategy that works well for all kinds of networks.  I find IcyTree's strategy works well for fairly busy ancestral recombination graphs, as opposed to smaller "schematic" diagrams representing individual HGT events (such as those on the extended newick website).

**Comment by hyanwong** [comment]
Thanks a lot. That's very helpful.
