### ISSUE TITLE
PhyloNet Networks, CLOSEP

### ISSUE THREAD

**Issue by stsmall** [tgvaughan/icytree#48]
Hi @tgvaughan 
Great program!
I am attempting to visualize a network produced by PhyloNet, but I keep running into this error:

Expected token CLOSEP but found COLON (:) at string position 76.
Error context:
"... 376594346172459::0.90332792356 ... "

Any advice on how to tweak the PhyloNet networks to avoid this error?

The offending network:
(((((LIK:1.7823822074818088,(FUN:1.3445425950227814)I8#H2:1.5376594346172459::0.9033279235672851)I4:2.123272756493314,(((LONG:1.591512866336745,PAR:1.1506980535138476)I6:0.8235624732461918,VAN:1.99876060
67094885)I5:0.008507112806777526)I3#H1:1.7947601921851537::0.49913588428968436)I2:0.010064524795769615,I3#H1:0.026409151098796137::0.5008641157103156)I1:1.1372864629725263,I8#H2:0.0759177689257327::0.096672076432
71492)I7:7.384595880714011,RIV:0.29826991779613143)I0;

**Comment by tgvaughan** [comment]
Hi Scott, glad you like it!

It seems the issue with PhyloNet is that it generates networks represented using their own [Rich Newick format](https://wiki.rice.edu/confluence/download/attachments/5216841/RichNewick-2012-02-16.pdf?version=1&modificationDate=1330535426168&api=v2). This format allows node labels to be followed by a sequence of colon-delimited numbers representing edge length, support, etc.  On the other hand, IcyTree follows the Newick format used in the nexus files generated by BEAST 1,2 which employs a [different annotation format](https://code.google.com/archive/p/beast-mcmc/wikis/NexusMetacommentFormat.wiki).

I'll see if I'm able to augment the parser to support Rich Newick format without conflicting with the existing formats.

**Comment by stsmall** [comment]
Thank you! That would be awesome! I am trying to compare PhyloNet networks run under MCMC_SEQ with the BEAST2 SpeciesNetwork.

**Comment by tgvaughan** [comment]
Hrm, I've (locally) hacked the parser to avoid the additional attributes present in the PhyloNet format so that at least the network parses and loads, but it looks a bit strange:

![tree](https://user-images.githubusercontent.com/512538/39843413-397d9f12-53eb-11e8-9aaa-de1d107dd038.png)

This is because the age of hybrid node pairs used to represent reticulations aren't matching up.  The Extended newick representation used by IcyTree uses two tree nodes to represent one network node, but the two tree nodes are usually given exactly the same time.  Looking at the format specification for PhyloNet, it seems as though its network representation is also based on Extended newick and should meet this same requirement, although I could be wrong.

Do you happen to have an example correct rendering of this network?  I've tried to load it into the latest version of Dendroscope which according to the PhyloNet home page is meant to be able to render PhyloNet output, but it seems to be having trouble parsing this one.

**Comment by stsmall** [comment]
Hi @tgvaughan,
I dont have it immediately at hand. I will work towards getting this one to render in dendroscope, since there is an option in PhyloNet, -di or some sort, that makes it compatible.

**Comment by stsmall** [comment]
This is what I got with Dendroscope:
![net](https://user-images.githubusercontent.com/2847551/39845427-d7f713da-53c3-11e8-8961-e45bb71c3387.png)

**Comment by tgvaughan** [comment]
Thanks. Is this a dendroscope rendering of the phylonet output with the compatibility option? And if so, could you also post the input to dendroscope? Because there's a good chance that the dendroscope compatible tree will also render correct in icytree.

**Comment by stsmall** [comment]
I couldnt get the di option to run on an already completed tree. In my understanding, it only removes the inheritance probabilities (https://wiki.rice.edu/confluence/pages/viewpage.action?pageId=8898533), which was what I did to get the tree to render in dendroscope. The tree without inheritance probs is the same as yours above when rendered in icytree. 
(((((LIK:1.7823822074818088,(FUN:1.3445425950227814)I8#H2:1.5376594346172459)I4:2.123272756493314,(((LONG:1.591512866336745,PAR:1.1506980535138476)I6:0.8235624732461918,VAN:1.9987606067094885)I5:0.008507112806777526)I3#H1:1.7947601921851537)I2:0.010064524795769615,I3#H1:0.026409151098796137)I1:1.1372864629725263,I8#H2:0.0759177689257327)I7:7.384595880714011,RIV:0.29826991779613143)I0;

**Comment by tgvaughan** [comment]
Hi Scott,  thanks for the info.

Yes the network above renders exactly the same as the previous network.  You can produce the IcytTree equivalent of the Dendroscope output by switching to a cladogram (Style->Layout->Cladogram):
![tree](https://user-images.githubusercontent.com/512538/39893570-75027f44-54a4-11e8-8f2e-a36cf6d0a294.png)

The problem still remains with the original network when edge lengths are included though (via Style->Layout->Standard time tree): the hybrid nodes are not at the same point in time, hence the diagonal edges.  If this proves a problem I could add an option to force one of these hybrid nodes to match the time of the other, although it's not clear which one should be treated as correct.

I think for now I'll just include the parsing modification to allow the phylonet trees to be plotted natively (without the -di option).  The cladogram option should be sufficient to compare topologies between the SpeciesNetwork and PhyloNet, I suppose?

**Comment by stsmall** [comment]
Thanks, that should work for what I need. I appreciate the support and quick responses!
