### ISSUE TITLE
Columnar metadata support on RHS 

### ISSUE THREAD

**Issue by tseemann** [tgvaughan/icytree#50]
Any plans to add support for aligned columns of metadata on the right hand side of a dendrogram?

Its seems to be the missing feature of most JS tree toolkits.

(I am impressed by the responsiveness and lack of bloat in icytree)

**Comment by tgvaughan** [comment]
Hi Torsten, no this isn't something I've considered - probably because it's not something I've personally needed.  It's an interesting idea though.  What's the context?  The emphasis of icytree is on rough and speedy visualisation of trees rather than assembling publication-quality figures, which is why many of the compositional features of other viewers are absent.

**Comment by andersgs** [comment]
@tgvaughan the context is for public health epidemiology. When we are doing contact tracing or define epidemiological clusters, it is useful to add metadata directly on the tree to visualise it in a phylo context. It is not for publication. Doesn't have to be high-end quality. Just needs to be fast, and readable.

**Comment by andersgs** [comment]
@tgvaughan just wondering if you had any thoughts on this. Ta.

**Comment by tgvaughan** [comment]
Hi @andersgs, given this is a fair way outside the original scope of the program, I'm hesitant to add this. Furthermore, it would break several underlying assumptions about what's on the page, meaning that a lot of the viewport handling code - which was honestly a huge headache to write - would need to be revised in order for it to work well.  In short, I can't really justify spending the time this would require, especially at the moment.

That said, if you would like to have a go at it yourself, I'd be happy to try to explain the relevant bits of the current codebase.  (All you need to do is hit the fork button and configure a github page and you'll have you're own private copy to hack on.)

Sorry I can't be more helpful!
