### ISSUE TITLE
disorganizated displaying of the Icytree Web

### ISSUE THREAD

**Issue by virologist** [tgvaughan/icytree#51]
Hi, Tim

I can't correctly open the icytree web.
I try it on different PC with different browsers. Here are the results of not works.
Chrome, Firefox, IE, Edge on 2 different windows 10 OS(1906)
Chrome on android
All these browsers are the latest.

However, it works well with my Apple devices, including Chrome and Safari on IOS.

The browsers console showing : Failed to load resource: net::ERR_CONNECTION_CLOSED
I tried to close all the extensions of Chrome, but nothing happens.

![image](https://user-images.githubusercontent.com/54756814/87870043-0c50e080-c9d7-11ea-8664-ff12647def66.png)

**Comment by tgvaughan** [comment]
Hi @virologist , it looks like your windows computer isn't able to connect to one of the servers from which the required javascript libraries (eg. jquery and jqueryui) are served.  (These are central content delivery networks that I don't run.)  Is it possible that one of these is being blocked on your network/operating system?

**Comment by virologist** [comment]
Solved! As you mentioned: being blocked by the local network. Thank you very much for your help. I struggling here for 2 days.
